export { HeroSection } from './hero-section'
export { BenefitsSection } from './benefits-section'
export { HowItWorksSection } from './how-it-works-section'
// export { TestimonialsSection } from './testimonials-section'
export { IntegrationsSection } from './integrations-section'
export { PricingSection } from './pricing-section'
export { AboutSection } from './about-section'
